<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Ternary-teal.ico</ApplicationIcon>
    <PackageIcon>Ternary-teal.png</PackageIcon>
    <VersionPrefix>10.0.7</VersionPrefix>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Ternary-teal.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Duende.AccessTokenManagement" />
    <PackageReference Include="Duende.AccessTokenManagement.OpenIdConnect" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Ternary.DataConversions" />
    <Using Include="HyRest.API" />
    <Using Include="HyRest.API.Models" />
    <Using Include="HyRest.DocumentManagement" />
    <Using Include="HyRest.Identity" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\resources\Ternary-teal.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include=".spec\admin-specification.json" />
    <None Include=".spec\document-management-specification.json" />
    <None Include=".spec\forms-specification.json" />
    <None Include=".spec\ids-specification.json" />
    <None Include=".spec\refitter-commands.txt" />
    <None Include=".spec\workflow-specification.json" />
    <None Include=".spec\workview-specification.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HyRest.Abstractions\HyRest.Abstractions.csproj" />
    <ProjectReference Include="..\HyRest.FileTypeMapping\HyRest.FileTypeMapping.csproj" />
  </ItemGroup>
</Project>